server:
  port: 8080

spring:
  application:
    name: encurtador-de-url

  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: urlshortener
    password: urlshortener
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

logging:
  level:
    root: INFO
    com.tulio.encurtadordeurl: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

